.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_getupvalue - liblua API documentation

.SH PROPERTIES
[-0, +(0|1), \fB-\fP]
.SH SYNOPSIS
const char *lua_getupvalue (lua_State *L, int funcindex, int n);

.SH DESCRIPTION

.sp
Gets information about a closure's upvalue.
(For Lua functions,
upvalues are the external local variables that the function uses,
and that are consequently included in its closure.)
\fBlua_getupvalue\fP gets the index \fBn\fP of an upvalue,
pushes the upvalue's value onto the stack,
and returns its name.
\fBfuncindex\fP points to the closure in the stack.
(Upvalues have no particular order,
as they are active through the whole function.
So, they are numbered in an arbitrary order.)

.sp
Returns \fBNULL\fP (and pushes nothing)
when the index is greater than the number of upvalues.
For C functions, this function uses the empty string \fB""\fP
as a name for all upvalues.