.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_pushlightuserdata - liblua API documentation

.SH PROPERTIES
[-0, +1, \fB-\fP]
.SH SYNOPSIS
void lua_pushlightuserdata (lua_State *L, void *p);

.SH DESCRIPTION

.sp
Pushes a light userdata onto the stack.

.sp
Userdata represent C values in Lua.
A \fBlight userdata\fP represents a pointer.
It is a value (like a number):
you do not create it, it has no individual metatable,
and it is not collected (as it was never created).
A light userdata is equal to "any"
light userdata with the same C address.