.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_rawequal - liblua API documentation

.SH PROPERTIES
[-0, +0, \fB-\fP]
.SH SYNOPSIS
int lua_rawequal (lua_State *L, int index1, int index2);

.SH DESCRIPTION

.sp
Returns 1 if the two values in acceptable indices \fBindex1\fP and
\fBindex2\fP are primitively equal
(that is, without calling metamethods).
Otherwise returns 0.
Also returns 0 if any of the indices are non valid.