.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_pushliteral - liblua API documentation

.SH PROPERTIES
[-0, +1, \fBm\fP]
.SH SYNOPSIS
void lua_pushliteral (lua_State *L, const char *s);

.SH DESCRIPTION

.sp
This macro is equivalent to \fBlua_pushlstring\fP,
but can be used only when \fBs\fP is a literal string.
In these cases, it automatically provides the string length.