.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_objlen - liblua API documentation

.SH PROPERTIES
[-0, +0, \fB-\fP]
.SH SYNOPSIS
size_t lua_objlen (lua_State *L, int index);

.SH DESCRIPTION

.sp
Returns the "length" of the value at the given acceptable index:
for strings, this is the string length;
for tables, this is the result of the length operator ('\fB#\fP');
for userdata, this is the size of the block of memory allocated
for the userdata;
for other values, it is 0.