.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_insert - liblua API documentation

.SH PROPERTIES
[-1, +1, \fB-\fP]
.SH SYNOPSIS
void lua_insert (lua_State *L, int index);

.SH DESCRIPTION

.sp
Moves the top element into the given valid index,
shifting up the elements above this index to open space.
Cannot be called with a pseudo-index,
because a pseudo-index is not an actual stack position.