.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_getfenv - liblua API documentation

.SH PROPERTIES
[-0, +1, \fB-\fP]
.SH SYNOPSIS
void lua_getfenv (lua_State *L, int index);

.SH DESCRIPTION

.sp
Pushes onto the stack the environment table of
the value at the given index.