.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_tostring - liblua API documentation

.SH PROPERTIES
[-0, +0, \fBm\fP]
.SH SYNOPSIS
const char *lua_tostring (lua_State *L, int index);

.SH DESCRIPTION

.sp
Equivalent to \fBlua_tolstring\fP with \fBlen\fP equal to \fBNULL\fP.