.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_remove - liblua API documentation

.SH PROPERTIES
[-1, +0, \fB-\fP]
.SH SYNOPSIS
void lua_remove (lua_State *L, int index);

.SH DESCRIPTION

.sp
Removes the element at the given valid index,
shifting down the elements above this index to fill the gap.
Cannot be called with a pseudo-index,
because a pseudo-index is not an actual stack position.