.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_isnumber - liblua API documentation

.SH PROPERTIES
[-0, +0, \fB-\fP]
.SH SYNOPSIS
int lua_isnumber (lua_State *L, int index);

.SH DESCRIPTION

.sp
Returns 1 if the value at the given acceptable index is a number
or a string convertible to a number,
and 0 otherwise.