.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_Integer - liblua API documentation

.SH SYNOPSIS
typedef ptrdiff_t lua_Integer;

.SH DESCRIPTION

.sp
The type used by the Lua API to represent integral values.

.sp
By default it is a \fBptrdiff_t\fP,
which is usually the largest signed integral type the machine handles
"comfortably".