.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_setfield - liblua API documentation

.SH PROPERTIES
[-1, +0, \fBe\fP]
.SH SYNOPSIS
void lua_setfield (lua_State *L, int index, const char *k);

.SH DESCRIPTION

.sp
Does the equivalent to \fBt[k] = v\fP,
where \fBt\fP is the value at the given valid index
and \fBv\fP is the value at the top of the stack.

.sp
This function pops the value from the stack.
As in Lua, this function may trigger a metamethod
for the "newindex" event.