.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_getlocal - liblua API documentation

.SH PROPERTIES
[-0, +(0|1), \fB-\fP]
.SH SYNOPSIS
const char *lua_getlocal (lua_State *L, lua_Debug *ar, int n);

.SH DESCRIPTION

.sp
Gets information about a local variable of a given activation record.
The parameter \fBar\fP must be a valid activation record that was
filled by a previous call to \fBlua_getstack\fP or
given as argument to a hook (see \fBlua_Hook\fP).
The index \fBn\fP selects which local variable to inspect
(1 is the first parameter or active local variable, and so on,
until the last active local variable).
\fBlua_getlocal\fP pushes the variable's value onto the stack
and returns its name.

.sp
Variable names starting with '\fB(\fP' (open parentheses)
represent internal variables
(loop control variables, temporaries, and C function locals).

.sp
Returns \fBNULL\fP (and pushes nothing)
when the index is greater than
the number of active local variables.