.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_Number - liblua API documentation

.SH SYNOPSIS
typedef double lua_Number;

.SH DESCRIPTION

.sp
The type of numbers in Lua.
By default, it is double, but that can be changed in \fBluaconf.h\fP.

.sp
Through the configuration file you can change
Lua to operate with another type for numbers (e.g., float or long).