.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_lessthan - liblua API documentation

.SH PROPERTIES
[-0, +0, \fBe\fP]
.SH SYNOPSIS
int lua_lessthan (lua_State *L, int index1, int index2);

.SH DESCRIPTION

.sp
Returns 1 if the value at acceptable index \fBindex1\fP is smaller
than the value at acceptable index \fBindex2\fP,
following the semantics of the Lua \fB<\fP operator
(that is, may call metamethods).
Otherwise returns 0.
Also returns 0 if any of the indices is non valid.