.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
lua_isfunction - liblua API documentation

.SH PROPERTIES
[-0, +0, \fB-\fP]
.SH SYNOPSIS
int lua_isfunction (lua_State *L, int index);

.SH DESCRIPTION

.sp
Returns 1 if the value at the given acceptable index is a function
(either C or Lua), and 0 otherwise.