.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_register - liblua API documentation

.SH PROPERTIES
[-(0|1), +1, \fBm\fP]
.SH SYNOPSIS
void luaL_register (lua_State *L, const char *libname, const luaL_Reg *l);

.SH DESCRIPTION

.sp
Opens a library.

.sp
When called with \fBlibname\fP equal to \fBNULL\fP,
it simply registers all functions in the list \fBl\fP
(see \fBluaL_Reg\fP) into the table on the top of the stack.

.sp
When called with a non-null \fBlibname\fP,
\fBluaL_register\fP creates a new table \fBt\fP,
sets it as the value of the global variable \fBlibname\fP,
sets it as the value of \fBpackage.loaded[libname]\fP,
and registers on it all functions in the list \fBl\fP.
If there is a table in \fBpackage.loaded[libname]\fP or in
variable \fBlibname\fP,
reuses this table instead of creating a new one.

.sp
In any case the function leaves the table
on the top of the stack.