.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_pushresult - liblua API documentation

.SH PROPERTIES
[-?, +1, \fBm\fP]
.SH SYNOPSIS
void luaL_pushresult (luaL_Buffer *B);

.SH DESCRIPTION

.sp
Finishes the use of buffer \fBB\fP leaving the final string on
the top of the stack.