.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_checknumber - liblua API documentation

.SH PROPERTIES
[-0, +0, \fBv\fP]
.SH SYNOPSIS
lua_Number luaL_checknumber (lua_State *L, int narg);

.SH DESCRIPTION

.sp
Checks whether the function argument \fBnarg\fP is a number
and returns this number.