.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_checkany - liblua API documentation

.SH PROPERTIES
[-0, +0, \fBv\fP]
.SH SYNOPSIS
void luaL_checkany (lua_State *L, int narg);

.SH DESCRIPTION

.sp
Checks whether the function has an argument
of any type (including \fBnil\fP) at position \fBnarg\fP.