.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_dofile - liblua API documentation

.SH PROPERTIES
[-0, +?, \fBm\fP]
.SH SYNOPSIS
int luaL_dofile (lua_State *L, const char *filename);

.SH DESCRIPTION

.sp
Loads and runs the given file.
It is defined as the following macro:

.ft C
     (luaL_loadfile(L, filename) || lua_pcall(L, 0, LUA_MULTRET, 0))
.ft P

.sp
It returns 0 if there are no errors
or 1 in case of errors.