.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_getmetatable - liblua API documentation

.SH PROPERTIES
[-0, +1, \fB-\fP]
.SH SYNOPSIS
void luaL_getmetatable (lua_State *L, const char *tname);

.SH DESCRIPTION

.sp
Pushes onto the stack the metatable associated with name \fBtname\fP
in the registry (see \fBluaL_newmetatable\fP).