.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_checkudata - liblua API documentation

.SH PROPERTIES
[-0, +0, \fBv\fP]
.SH SYNOPSIS
void *luaL_checkudata (lua_State *L, int narg, const char *tname);

.SH DESCRIPTION

.sp
Checks whether the function argument \fBnarg\fP is a userdata
of the type \fBtname\fP (see \fBluaL_newmetatable\fP).