.TH "liblua" "3" "Jan 25, 2016" "5.1.5" "lua API documentation"
.SH NAME
luaL_addlstring - liblua API documentation

.SH PROPERTIES
[-0, +0, \fBm\fP]
.SH SYNOPSIS
void luaL_addlstring (luaL_Buffer *B, const char *s, size_t l);

.SH DESCRIPTION

.sp
Adds the string pointed to by \fBs\fP with length \fBl\fP to
the buffer \fBB\fP
(see \fBluaL_Buffer\fP).
The string may contain embedded zeros.